### ISSUE TITLE
natives\x64\objectroot\scene\location\rpd\level_100\environments\st4_313_0\gimmick.scn.19 only works on GUI 

### ISSUE THREAD

**Issue by Namsku** [czastack/RszTool#16]
My code

        public ScnFile ReadScnFile(string path)
        {
            RszFileOption option = new(GameName.re2);
            FileHandler fileHandler = new FileHandler(path);
            
            ScnFile scnFile = new(option, fileHandler);
            scnFile.Read();

            return scnFile;
        }

       Will crash at
       
                   scnFile.Read();

<img width="1516" alt="image" src="https://github.com/czastack/RszTool/assets/144552240/7e09f862-9538-4019-92e8-7e23fc258c96">

[gimmick.scn.zip](https://github.com/user-attachments/files/15836321/gimmick.scn.zip)

Malformed SCN file ?

**Comment by Namsku** [comment]
For the context

<img width="963" alt="image" src="https://github.com/czastack/RszTool/assets/144552240/60c0d911-7874-4437-9a69-885efbe2e550">

Same file in the GUI is working, so i'm confused

**Comment by czastack** [comment]
@Namsku I can not recurrence the issue with your gimmick.scn.zip. I see path in the first image is st317_0, the second is st4_313_0.

**Comment by Namsku** [comment]
My bad, I will retry tonight, maybe it's on my side. If it's a mistake that i have done, i'll close the ticket. I'll keep you in touch

**Comment by Namsku** [comment]
it was definitely an error on my side
